### ISSUE TITLE
Add strict mode for Bindings

### ISSUE THREAD

**Issue by westei** [tkurz/nodekeeper#4]
Add the possibility to define the processing mode `strict=ture/false` for bindings.

This will be used for error handling in processing. If a bindings fails (e.g. because of an exception)

* in `struct=true` mode the execution of the Action will be cancelled
* in `strict=false` mode the execution will continue and the action will be performed with this binding missing.

This allows the user to define if a binding is required or the action is still valid if a binding is missing. This information can be used by the implementation to correctly deal with exceptions.

**Comment by tkurz** [comment]
I started to implement

**Comment by tkurz** [comment]
Bindings can no set to strict with attribute strict="true", which means that an action that uses the binding is not executed if binding cannot be set. Default mode is strict="false"
